Adding name of the dynamoDB to backend config. Checking for ENV when running the makefile

diff --git a/Terraform/Makefile b/Terraform/Makefile
--- a/Terraform/Makefile
+++ b/Terraform/Makefile
@@ -1,23 +1,16 @@
-GREEN := '\033[0;32m'
-
-define Log =
-echo $(2) $(1)
-endef
-
-define info =
-echo -e '$(GREEN) $(1)'
-endef
 
 # tf:init is terraform init
-init:
-	@terraform init -var="enviroments/tfvars/$(ENV).tfvars" -backend-config="enviroments/backend/$(ENV).conf"
 .PHONY: init
+init:
+	@test -n "$(ENV)" || (echo "\033[91m Missing ENV" )
+	@terraform init -var="enviroments/tfvars/$(ENV).tfvars" -backend-config="enviroments/backend/$(ENV).conf"
 
 clean:
 	rm -rf .terraform
 .PHONY: clean
 
 plan:
+	@test -n "$(ENV)" || ERROR
 	@terraform plan -out plan.out
 .PHONEY: plan
 
@@ -28,3 +21,5 @@ build: clean init plan
 apply:
 	@terraform apply -auto-approve -input=false plan.out
 
+ERROR:
+	$(error Missing ENV)
